---
title: "main.R"
author: "Gayatri Shahane"
date: "4/22/2020"
output:
  word_document: default
  pdf_document: default
  html_document: default
---

```{r message=FALSE, warning=FALSE}

#Loading Libraries
library(tidyverse)
library(readr)
library(lubridate)

#TASK1
files <- list.files(path = "/Users/gayatrishahane/Desktop/GS_CQuant/GS_CQuant_Solution/historicalPriceData", pattern = "*.csv", full.names = TRUE)
PriceData <- sapply(files, read_csv, simplify=FALSE) %>% 
bind_rows()
PriceData <- PriceData %>% arrange(Date)

```

```{r}

#TASK2
view(PriceData)
AvgMonth <- PriceData %>% 
  separate(Date, c("Date", "Time"), " ") %>% 
  separate(Date,c("Year", "Month", "Day"), "-") %>%
  group_by(SettlementPoint, Year, Month) %>% 
  summarise(AveragePrice = mean(Price))

#TASK3
write_csv(AvgMonth,'AveragePriceByMonth.csv', col_names = TRUE)

```

```{r}

#TASK4
HourlyVolatalityByYear <- PriceData %>% 
  filter(Price>0) %>% 
  filter(str_detect(SettlementPoint, "^HB")) %>% 
  group_by(SettlementPoint, year(Date)) %>% 
  summarise(HourlyVolatility = sd(log(Price))) %>% 
  rename(Year = `year(Date)`)

#TASK5
write_csv(HourlyVolatalityByYear,'HourlyVolatilityByYear.csv', col_names = TRUE)

#TASK6
MaxVolatality <- HourlyVolatalityByYear %>% 
  group_by(Year) %>% 
  filter(HourlyVolatility == max(HourlyVolatility)) %>%
  arrange(Year) %>% 
  write_csv('MaxVolatilityByYear.csv')

```

```{r}
#TASK7
FormattedPrice <- PriceData %>%
  mutate(Time = as.integer(hour(Date))+1, Date = date(Date)) %>% 
  spread(Time, Price) %>% 
  rename(Variable = SettlementPoint) %>% 
  select(c(2,1,3:26))

#Naming the Columns
 newcolnames <- colnames(FormattedPrice)
  for (i in 3:length(newcolnames)){
    newcolnames[i] = paste('X', newcolnames[i])
  }
  colnames(FormattedPrice) <- newcolnames
  
#Writing the csv files 
  for(var1 in unique(FormattedPrice$Variable)){
    uni <- FormattedPrice %>% 
      filter(Variable == var1)
    uni %>% 
      write_csv(paste0('spot_',var1, '.csv'))
  }
#Creating new sub directory was causing path error. Hence, all the csv files are in the same main file.
```
```{r}
#Bonus Mean Plots

MeanPlot <- AvgMonth %>% 
  mutate(Day = '01') %>% 
  unite(Date, Year, Month, Day, sep = "-") %>% 
  mutate(Date = date(Date))

#Average Prices for Settlement Hubs

HubPlot <- MeanPlot %>% 
  filter(str_detect(SettlementPoint, "^HB")) %>% 
  ggplot(mapping = aes(x= Date, y = AveragePrice, color = SettlementPoint)) +
  geom_line() +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_x_date(date_breaks = "months" , date_labels = "%Y-%m-%d") +
  ggsave('SettlementHubAveragePriceByMonth.png')

#Average Prices for Load Zones

LoadZonePlot <- MeanPlot %>% 
  filter(str_detect(SettlementPoint, "^LZ")) %>% 
  ggplot(mapping = aes(x= Date, y = AveragePrice, color = SettlementPoint)) +
  geom_line() +
  theme(axis.text.x = element_text(angle = 90)) +
  scale_x_date(date_breaks = "months" , date_labels = "%Y-%m-%d") +
  ggsave('LoadZoneAveragePriceByMonth.png')


```
```{r}
#Bonus Volatality Plot

VolPLot1 <- ggplot(data = HourlyVolatalityByYear) + 
  geom_point(mapping = aes(x = Year, y = HourlyVolatility, color = SettlementPoint))+
  geom_line(mapping = aes(x = Year, y = HourlyVolatility, color = SettlementPoint))+
  ggtitle('Settlement Hub Hourly Volatility by Year')+
  ggsave('SettlementHubHourlyVolatility.png')
  
```

```{r}
#Bonus Hourly Shape Profile Computation

HourlyShape <- PriceData %>% 
  mutate(Time = as.integer(hour(Date))+1, Date = date(Date)) %>% 
  mutate(Day = day(Date), Month = month(Date)) %>% 
  group_by(SettlementPoint, Month, Day, Time) %>%
    summarise(AvgPrice = mean(Price)) %>% 
    group_by(SettlementPoint, Month, Day) %>%
    mutate(NormalAvgPrice = AvgPrice/mean(AvgPrice)) %>% 
    select(SettlementPoint, Month, Day, Time, NormalAvgPrice)

#Writing the csv files

for(var2 in unique(HourlyShape$SettlementPoint)){
  uni <- HourlyShape %>% 
      filter(SettlementPoint == var2)
    uni %>% 
      write_csv(paste0('profile_',var2, '.csv'))
}

```

```{r}
#Bonus Analysis

#Plot1
ggplot(data = PriceData) + 
  geom_point(mapping = aes(x = Date, y = Price, color = SettlementPoint)) + 
  facet_wrap(~ SettlementPoint) +
  ggsave('BonusAnalysis1.png')


````

